---
kind: Service
apiVersion: v1
metadata:
  name: simple-json-persistence-service
spec:
  selector:
    app: simple-json-persistence-server
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 8081
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-json-persistence-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-json-persistence-server
    spec:
      containers:
        - name: simple-json-persistence-server
          image: revfwd:1.0
          imagePullPolicy: Never 
          ports:
            - containerPort: 8081